services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - default:/var/lib/postgresql/data
    networks:
      - default

  kong_migrations:
    container_name: ${KONG_MIGRATIONS_CONTAINER_NAME}
    image: ${KONG_IMAGE_NAME}:${KONG_IMAGE_VERSION}
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
      - KONG_CASSANDRA_CONTACT_POINTS=postgres
    networks:
      - default
    depends_on:
      - postgres
    command: kong migrations bootstrap

  kong:
    container_name: ${KONG_CONTAINER_NAME}
    image: ${KONG_IMAGE_NAME}:${KONG_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
      - KONG_CASSANDRA_CONTACT_POINTS=postgres
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:${KONG_ADMIN_HTTP_PORT}, 0.0.0.0:${KONG_ADMIN_HTTPS_PORT} ssl
    ports:
      - ${KONG_HTTP_PORT}:8000
      - ${KONG_HTTPS_PORT}:8443
      - ${KONG_ADMIN_HTTP_PORT}:8001
      - ${KONG_ADMIN_HTTPS_PORT}:8444
    volumes:
      - kong_data:/usr/local/kong
    networks:
      - default
    depends_on:
      - kong_migrations

  konga:
    container_name: ${KONGA_CONTAINER_NAME}
    image: ${KONGA_IMAGE_NAME}:${KONGA_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - NODE_ENV=${KONGA_NODE_ENV}
    ports:
      - ${KONGA_HTTP_PORT}:1337
    volumes:
      - konga_data:/app/kongadata
    networks:
      - default
    depends_on:
      - kong

networks:
  default:
    name: ${KONG_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${POSTGRES_CONTAINER_NAME}_data
    driver: local
  kong_data:
    name: ${KONG_CONTAINER_NAME}_data
    driver: local
  konga_data:
    name: ${KONGA_CONTAINER_NAME}_data
    driver: local