name: ${GLOBAL_NAME}

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - default:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

  kong_migrations:
    container_name: ${KONG_MIGRATIONS_CONTAINER_NAME}
    image: ${KONG_IMAGE_NAME}:${KONG_IMAGE_VERSION}
    restart: on-failure
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_CASSANDRA_CONTACT_POINTS=${KONG_CASSANDRA_CONTACT_POINTS}
    networks:
      - default
    depends_on:
      - postgres
    command: kong migrations bootstrap

  kong:
    container_name: ${KONG_CONTAINER_NAME}
    image: ${KONG_IMAGE_NAME}:${KONG_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - LC_CTYPE=${KONG_LC_CTYPE}
      - LC_ALL=${KONG_LC_ALL}
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_CASSANDRA_CONTACT_POINTS=${KONG_CASSANDRA_CONTACT_POINTS}
      - KONG_PROXY_ACCESS_LOG=${KONG_PROXY_ACCESS_LOG}
      - KONG_ADMIN_ACCESS_LOG=${KONG_ADMIN_ACCESS_LOG}
      - KONG_PROXY_ERROR_LOG=${KONG_PROXY_ERROR_LOG}
      - KONG_ADMIN_ERROR_LOG=${KONG_ADMIN_ERROR_LOG}
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN}
    ports:
      - ${KONG_HTTP_PORT}:8000
      - ${KONG_HTTPS_PORT}:8443
      - ${KONG_ADMIN_HTTP_PORT}:8001
      - ${KONG_ADMIN_HTTPS_PORT}:8444
    volumes:
      - kong_data:/usr/local/kong
    networks:
      - default
    depends_on:
      - kong_migrations
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

  konga:
    container_name: ${KONGA_CONTAINER_NAME}
    image: ${KONGA_IMAGE_NAME}:${KONGA_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - NODE_ENV=${KONGA_NODE_ENV}
      - DB_ADAPTER=${KONGA_DB_ADAPTER}
      - DB_HOST=${KONGA_DB_HOST}
      - DB_USER=${KONGA_DB_USER}
      - DB_PASSWORD=${KONGA_DB_PASSWORD}
      - DB_DATABASE=${KONGA_DB_DATABASE}
      - DB_PORT=${KONGA_DB_PORT}
    ports:
      - ${KONGA_HTTP_PORT}:1337
    volumes:
      - konga_data:/app/kongadata
    networks:
      - default
    depends_on:
      - kong
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1337/api/health"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: ${GLOBAL_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${POSTGRES_CONTAINER_NAME}_data
    driver: local
  kong_data:
    name: ${KONG_CONTAINER_NAME}_data
    driver: local
  konga_data:
    name: ${KONGA_CONTAINER_NAME}_data
    driver: local